name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@master
      - name: Xdebug Action
        uses: MilesChou/docker-xdebug@v1.1.0        
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v9
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
